export interface AirportInfo {
  city: string;
  country: string;
  image?: string;
}

export const AIRPORTS_MAP: Record<string, AirportInfo> = {
  // España
  MAD: { city: 'Madrid', country: 'España' },
  BCN: { city: 'Barcelona', country: 'España' },
  VLC: { city: 'Valencia', country: 'España' },
  AGP: { city: 'Málaga', country: 'España' },
  SVQ: { city: 'Sevilla', country: 'España' },
  BIO: { city: 'Bilbao', country: 'España' },
  ALC: { city: 'Alicante', country: 'España' },
  SCQ: { city: 'Santiago de Compostela', country: 'España' },
  PMI: { city: 'Palma de Mallorca', country: 'España' },
  IBZ: { city: 'Ibiza', country: 'España' },
  MAH: { city: 'Menorca', country: 'España' },
  TFN: { city: 'Tenerife Norte', country: 'España' },
  TFS: { city: 'Tenerife Sur', country: 'España' },
  LPA: { city: 'Gran Canaria', country: 'España' },
  ACE: { city: 'Lanzarote', country: 'España' },
  FUE: { city: 'Fuerteventura', country: 'España' },
  SPC: { city: 'La Palma', country: 'España' },
  SDR: { city: 'Santander', country: 'España' },
  VGO: { city: 'Vigo', country: 'España' },
  OVD: { city: 'Asturias', country: 'España' },
  ZAZ: { city: 'Zaragoza', country: 'España' },
  GRX: { city: 'Granada', country: 'España' },
  MJV: { city: 'Murcia', country: 'España' },
  XRY: { city: 'Jerez de la Frontera', country: 'España' },
  REU: { city: 'Reus (Tarragona)', country: 'España' },
  GRO: { city: 'Girona', country: 'España' },

  // Italia
  MIL: { city: 'Milán', country: 'Italia' },
  MXP: { city: 'Milán (Malpensa)', country: 'Italia' },
  LIN: { city: 'Milán (Linate)', country: 'Italia' },
  BGY: { city: 'Milán (Bérgamo)', country: 'Italia' },
  ROM: { city: 'Roma', country: 'Italia' },
  FCO: { city: 'Roma (Fiumicino)', country: 'Italia' },
  CIA: { city: 'Roma (Ciampino)', country: 'Italia' },
  NAP: { city: 'Nápoles', country: 'Italia' },
  VCE: { city: 'Venecia', country: 'Italia' },
  TSF: { city: 'Venecia (Treviso)', country: 'Italia' },
  FLR: { city: 'Florencia', country: 'Italia' },
  BLQ: { city: 'Bolonia', country: 'Italia' },
  TRN: { city: 'Turín', country: 'Italia' },
  BRI: { city: 'Bari (Puglia)', country: 'Italia' },
  PMO: { city: 'Palermo (Sicilia)', country: 'Italia' },
  CTA: { city: 'Catania (Sicilia)', country: 'Italia' },
  OLB: { city: 'Olbia (Cerdeña)', country: 'Italia' },
  CAG: { city: 'Cagliari (Cerdeña)', country: 'Italia' },
  AHO: { city: 'Alguer / Alghero (Cerdeña)', country: 'Italia' },
  PSA: { city: 'Pisa (Toscana)', country: 'Italia' },
  TRS: { city: 'Trieste', country: 'Italia' },
  SUF: { city: 'Lamezia Terme', country: 'Italia' },
  VRN: { city: 'Verona', country: 'Italia' },
  PEG: { city: 'Perugia', country: 'Italia' },
  PSR: { city: 'Pescara', country: 'Italia' },
  BZO: { city: 'Bolzano', country: 'Italia' },

  // Francia
  PAR: { city: 'París', country: 'Francia' },
  CDG: { city: 'París (Charles de Gaulle)', country: 'Francia' },
  ORY: { city: 'París (Orly)', country: 'Francia' },
  BVA: { city: 'París (Beauvais)', country: 'Francia' },
  NCE: { city: 'Niza', country: 'Francia' },
  LYS: { city: 'Lyon', country: 'Francia' },
  MRS: { city: 'Marsella', country: 'Francia' },
  BOD: { city: 'Burdeos', country: 'Francia' },
  TLS: { city: 'Toulouse', country: 'Francia' },
  NTE: { city: 'Nantes', country: 'Francia' },
  MPL: { city: 'Montpellier', country: 'Francia' },
  BIQ: { city: 'Biarritz', country: 'Francia' },
  BZR: { city: 'Béziers', country: 'Francia' },
  LIG: { city: 'Limoges', country: 'Francia' },
  CCF: { city: 'Carcasona', country: 'Francia' },
  PGF: { city: 'Perpiñán', country: 'Francia' },
  RNS: { city: 'Rennes', country: 'Francia' },
  SXB: { city: 'Estrasburgo', country: 'Francia' },

  // Reino Unido & Irlanda
  LON: { city: 'Londres', country: 'Reino Unido' },
  LHR: { city: 'Londres (Heathrow)', country: 'Reino Unido' },
  LGW: { city: 'Londres (Gatwick)', country: 'Reino Unido' },
  STN: { city: 'Londres (Stansted)', country: 'Reino Unido' },
  LTN: { city: 'Londres (Luton)', country: 'Reino Unido' },
  SEN: { city: 'Londres (Southend)', country: 'Reino Unido' },
  EDI: { city: 'Edimburgo', country: 'Reino Unido' },
  MAN: { city: 'Mánchester', country: 'Reino Unido' },
  BRS: { city: 'Bristol', country: 'Reino Unido' },
  BHX: { city: 'Birmingham', country: 'Reino Unido' },
  GLA: { city: 'Glasgow', country: 'Reino Unido' },
  PIK: { city: 'Glasgow (Prestwick)', country: 'Reino Unido' },
  LPL: { city: 'Liverpool', country: 'Reino Unido' },
  NCL: { city: 'Newcastle', country: 'Reino Unido' },
  BOH: { city: 'Bournemouth', country: 'Reino Unido' },
  EXT: { city: 'Exeter', country: 'Reino Unido' },
  DUB: { city: 'Dublín', country: 'Irlanda' },
  ORK: { city: 'Cork', country: 'Irlanda' },
  SNN: { city: 'Shannon', country: 'Irlanda' },
  NOC: { city: 'Knock', country: 'Irlanda' },
  BFS: { city: 'Belfast', country: 'Reino Unido' },

  // Alemania, Austria, Suiza
  BER: { city: 'Berlín', country: 'Alemania' },
  MUC: { city: 'Múnich', country: 'Alemania' },
  FRA: { city: 'Fráncfort', country: 'Alemania' },
  HHN: { city: 'Fráncfort (Hahn)', country: 'Alemania' },
  DUS: { city: 'Düsseldorf', country: 'Alemania' },
  NRN: { city: 'Düsseldorf (Weeze)', country: 'Alemania' },
  HAM: { city: 'Hamburgo', country: 'Alemania' },
  CGN: { city: 'Colonia / Bonn', country: 'Alemania' },
  STR: { city: 'Stuttgart', country: 'Alemania' },
  NUE: { city: 'Núremberg', country: 'Alemania' },
  FMM: { city: 'Memmingen (Múnich Oeste)', country: 'Alemania' },
  BRE: { city: 'Bremen', country: 'Alemania' },
  HAJ: { city: 'Hannover', country: 'Alemania' },
  DTM: { city: 'Dortmund', country: 'Alemania' },
  FKB: { city: 'Karlsruhe / Baden-Baden', country: 'Alemania' },
  PAD: { city: 'Paderborn', country: 'Alemania' },
  VIE: { city: 'Viena', country: 'Austria' },
  SZG: { city: 'Salzburgo', country: 'Austria' },
  INN: { city: 'Innsbruck', country: 'Austria' },
  GRZ: { city: 'Graz', country: 'Austria' },
  LNZ: { city: 'Linz', country: 'Austria' },
  ZRH: { city: 'Zúrich', country: 'Suiza' },
  GVA: { city: 'Ginebra', country: 'Suiza' },
  BSL: { city: 'Basilea / Mulhouse', country: 'Suiza' },

  // Países Bajos, Bélgica & Portugal
  AMS: { city: 'Ámsterdam', country: 'Países Bajos' },
  EIN: { city: 'Eindhoven', country: 'Países Bajos' },
  RTM: { city: 'Róterdam', country: 'Países Bajos' },
  GRQ: { city: 'Groninga', country: 'Países Bajos' },
  BRU: { city: 'Bruselas', country: 'Bélgica' },
  CRL: { city: 'Bruselas (Charleroi)', country: 'Bélgica' },
  ANR: { city: 'Amberes', country: 'Bélgica' },
  LGG: { city: 'Lieja', country: 'Bélgica' },
  LIS: { city: 'Lisboa', country: 'Portugal' },
  OPO: { city: 'Oporto', country: 'Portugal' },
  FAO: { city: 'Faro (Algarve)', country: 'Portugal' },
  FNC: { city: 'Funchal (Madeira)', country: 'Portugal' },
  PDL: { city: 'Ponta Delgada (Azores)', country: 'Portugal' },

  // Europa Central, del Este & Bálticos
  PRG: { city: 'Praga', country: 'Rep. Checa' },
  BRQ: { city: 'Brno', country: 'Rep. Checa' },
  OSR: { city: 'Ostrava', country: 'Rep. Checa' },
  BUD: { city: 'Budapest', country: 'Hungría' },
  DEB: { city: 'Debrecen', country: 'Hungría' },
  WAW: { city: 'Varsovia', country: 'Polonia' },
  WMI: { city: 'Varsovia (Modlin)', country: 'Polonia' },
  KRK: { city: 'Cracovia', country: 'Polonia' },
  WRO: { city: 'Wroclaw', country: 'Polonia' },
  GDN: { city: 'Gdansk', country: 'Polonia' },
  POZ: { city: 'Poznan', country: 'Polonia' },
  KTW: { city: 'Katowice', country: 'Polonia' },
  RZE: { city: 'Rzeszow', country: 'Polonia' },
  LUZ: { city: 'Lublin', country: 'Polonia' },
  BTS: { city: 'Bratislava', country: 'Eslovaquia' },
  KSC: { city: 'Kosice', country: 'Eslovaquia' },
  LJU: { city: 'Liubliana', country: 'Eslovenia' },
  OSL: { city: 'Oslo', country: 'Noruega' },
  TRF: { city: 'Oslo (Torp)', country: 'Noruega' },
  BGO: { city: 'Bergen', country: 'Noruega' },
  SVG: { city: 'Stavanger', country: 'Noruega' },
  TRD: { city: 'Trondheim', country: 'Noruega' },
  STO: { city: 'Estocolmo', country: 'Suecia' },
  ARN: { city: 'Estocolmo (Arlanda)', country: 'Suecia' },
  NYO: { city: 'Estocolmo (Skavsta)', country: 'Suecia' },
  GOT: { city: 'Gotemburgo', country: 'Suecia' },
  MMX: { city: 'Malmö', country: 'Suecia' },
  CPH: { city: 'Copenhague', country: 'Dinamarca' },
  BLL: { city: 'Billund', country: 'Dinamarca' },
  AAR: { city: 'Aarhus', country: 'Dinamarca' },
  HEL: { city: 'Helsinki', country: 'Finlandia' },
  TMP: { city: 'Tampere', country: 'Finlandia' },
  TKU: { city: 'Turku', country: 'Finlandia' },
  REK: { city: 'Reikiavik', country: 'Islandia' },
  KEF: { city: 'Reikiavik (Keflavik)', country: 'Islandia' },
  RIX: { city: 'Riga', country: 'Letonia' },
  TLL: { city: 'Tallin', country: 'Estonia' },
  VNO: { city: 'Vilna', country: 'Lituania' },
  KUN: { city: 'Kaunas', country: 'Lituania' },
  PLQ: { city: 'Palanga', country: 'Lituania' },

  // Grecia, Balcanes & Turquía
  ATH: { city: 'Atenas', country: 'Grecia' },
  SKG: { city: 'Salónica', country: 'Grecia' },
  HER: { city: 'Heraclión (Creta)', country: 'Grecia' },
  CHQ: { city: 'Chania (Creta)', country: 'Grecia' },
  RHO: { city: 'Rodas', country: 'Grecia' },
  JTR: { city: 'Santorini', country: 'Grecia' },
  JMK: { city: 'Mikonos', country: 'Grecia' },
  CFU: { city: 'Corfú', country: 'Grecia' },
  KGS: { city: 'Kos', country: 'Grecia' },
  ZTH: { city: 'Zakynthos (Zante)', country: 'Grecia' },
  KLX: { city: 'Kalamata', country: 'Grecia' },
  PVK: { city: 'Preveza / Lefkada', country: 'Grecia' },
  LCA: { city: 'Larnaca', country: 'Chipre' },
  PFO: { city: 'Pafos', country: 'Chipre' },
  IST: { city: 'Estambul', country: 'Turquía' },
  SAW: { city: 'Estambul (Sabiha Gökçen)', country: 'Turquía' },
  AYT: { city: 'Antalya', country: 'Turquía' },
  DLM: { city: 'Dalaman', country: 'Turquía' },
  BJV: { city: 'Bodrum', country: 'Turquía' },
  ADB: { city: 'Izmir', country: 'Turquía' },
  ESB: { city: 'Ankara', country: 'Turquía' },
  ZAG: { city: 'Zagreb', country: 'Croacia' },
  SPU: { city: 'Split', country: 'Croacia' },
  DBV: { city: 'Dubrovnik', country: 'Croacia' },
  ZAD: { city: 'Zadar', country: 'Croacia' },
  PUY: { city: 'Pula', country: 'Croacia' },
  RJK: { city: 'Rijeka', country: 'Croacia' },
  BEG: { city: 'Belgrado', country: 'Serbia' },
  INI: { city: 'Nis', country: 'Serbia' },
  TIA: { city: 'Tirana', country: 'Albania' },
  SOF: { city: 'Sofía', country: 'Bulgaria' },
  VAR: { city: 'Varna', country: 'Bulgaria' },
  BOJ: { city: 'Burgas', country: 'Bulgaria' },
  PDV: { city: 'Plovdiv', country: 'Bulgaria' },
  BUH: { city: 'Bucarest', country: 'Rumania' },
  OTP: { city: 'Bucarest (Henri Coandă)', country: 'Rumania' },
  BBU: { city: 'Bucarest (Băneasa)', country: 'Rumania' },
  CLJ: { city: 'Cluj-Napoca', country: 'Rumania' },
  TSR: { city: 'Timisoara', country: 'Rumania' },
  IAS: { city: 'Iasi', country: 'Rumania' },
  SBZ: { city: 'Sibiu', country: 'Rumania' },
  CJJ: { city: 'Craiova', country: 'Rumania' },
  SJJ: { city: 'Sarajevo', country: 'Bosnia' },
  TZL: { city: 'Tuzla', country: 'Bosnia' },
  OMO: { city: 'Mostar', country: 'Bosnia' },
  TGD: { city: 'Podgorica', country: 'Montenegro' },
  TIV: { city: 'Tivat', country: 'Montenegro' },
  SKP: { city: 'Skopje', country: 'Macedonia del Norte' },
  OHD: { city: 'Ohrid', country: 'Macedonia del Norte' },
  PRN: { city: 'Pristina', country: 'Kosovo' },
  KUT: { city: 'Kutaisi', country: 'Georgia' },
  TBS: { city: 'Tiflis', country: 'Georgia' },
  BUS: { city: 'Batumi', country: 'Georgia' },
  EVN: { city: 'Ereván', country: 'Armenia' },

  // Marruecos & África
  RAK: { city: 'Marrakech', country: 'Marruecos' },
  CMN: { city: 'Casablanca', country: 'Marruecos' },
  TNG: { city: 'Tánger', country: 'Marruecos' },
  FEZ: { city: 'Fez', country: 'Marruecos' },
  AGA: { city: 'Agadir', country: 'Marruecos' },
  NDR: { city: 'Nador', country: 'Marruecos' },
  OUJ: { city: 'Oujda', country: 'Marruecos' },
  OZZ: { city: 'Ouarzazate', country: 'Marruecos' },
  RBA: { city: 'Rabat', country: 'Marruecos' },
  AHU: { city: 'Alhucemas', country: 'Marruecos' },
  TUN: { city: 'Túnez', country: 'Túnez' },
  NBE: { city: 'Enfidha / Hammamet', country: 'Túnez' },
  DJE: { city: 'Yerba', country: 'Túnez' },
  MIR: { city: 'Monastir', country: 'Túnez' },
  ALG: { city: 'Argel', country: 'Argelia' },
  ORN: { city: 'Orán', country: 'Argelia' },
  CAI: { city: 'El Cairo', country: 'Egipto' },
  HRG: { city: 'Hurghada', country: 'Egipto' },
  SSH: { city: 'Sharm el-Sheikh', country: 'Egipto' },
  LXR: { city: 'Lúxor', country: 'Egipto' },
  MLA: { city: 'Malta', country: 'Malta' },

  // América
  JFK: { city: 'Nueva York (JFK)', country: 'EE.UU.' },
  EWR: { city: 'Nueva York (Newark)', country: 'EE.UU.' },
  LGA: { city: 'Nueva York (LaGuardia)', country: 'EE.UU.' },
  MIA: { city: 'Miami', country: 'EE.UU.' },
  FLL: { city: 'Fort Lauderdale', country: 'EE.UU.' },
  LAX: { city: 'Los Ángeles', country: 'EE.UU.' },
  SFO: { city: 'San Francisco', country: 'EE.UU.' },
  ORD: { city: 'Chicago (O\'Hare)', country: 'EE.UU.' },
  BOS: { city: 'Boston', country: 'EE.UU.' },
  IAD: { city: 'Washington D.C.', country: 'EE.UU.' },
  MCO: { city: 'Orlando', country: 'EE.UU.' },
  LAS: { city: 'Las Vegas', country: 'EE.UU.' },
  CUN: { city: 'Cancún', country: 'México' },
  MEX: { city: 'Ciudad de México', country: 'México' },
  BOG: { city: 'Bogotá', country: 'Colombia' },
  MDE: { city: 'Medellín', country: 'Colombia' },
  LIM: { city: 'Lima', country: 'Perú' },
  EZE: { city: 'Buenos Aires (Ezeiza)', country: 'Argentina' },
  AEP: { city: 'Buenos Aires (Aeroparque)', country: 'Argentina' },
  SCL: { city: 'Santiago de Chile', country: 'Chile' },
  GRU: { city: 'São Paulo (Guarulhos)', country: 'Brasil' },
  GIG: { city: 'Río de Janeiro', country: 'Brasil' },
  HAV: { city: 'La Habana', country: 'Cuba' },
  SDQ: { city: 'Santo Domingo', country: 'Rep. Dominicana' },
  PUJ: { city: 'Punta Cana', country: 'Rep. Dominicana' },
  SJU: { city: 'San Juan', country: 'Puerto Rico' },

  // Oriente Medio & Asia
  DXB: { city: 'Dubái', country: 'EAU' },
  DOH: { city: 'Doha', country: 'Qatar' },
  AUH: { city: 'Abu Dabi', country: 'EAU' },
  AMM: { city: 'Ammán', country: 'Jordania' },
  TLV: { city: 'Tel Aviv', country: 'Israel' },
  BEY: { city: 'Beirut', country: 'Líbano' },
  BKK: { city: 'Bangkok (Suvarnabhumi)', country: 'Tailandia' },
  DMK: { city: 'Bangkok (Don Mueang)', country: 'Tailandia' },
  HKT: { city: 'Phuket', country: 'Tailandia' },
  CNX: { city: 'Chiang Mai', country: 'Tailandia' },
  SIN: { city: 'Singapur', country: 'Singapur' },
  KUL: { city: 'Kuala Lumpur', country: 'Malasia' },
  HKG: { city: 'Hong Kong', country: 'Hong Kong' },
  NRT: { city: 'Tokio (Narita)', country: 'Japón' },
  HND: { city: 'Tokio (Haneda)', country: 'Japón' },
  KIX: { city: 'Osaka', country: 'Japón' },
  ICN: { city: 'Seúl (Incheon)', country: 'Corea del Sur' },
  DEL: { city: 'Delhi', country: 'India' },
  BOM: { city: 'Mumbai', country: 'India' },
  DPS: { city: 'Bali (Denpasar)', country: 'Indonesia' },
  CGK: { city: 'Yakarta', country: 'Indonesia' },
  MNL: { city: 'Manila', country: 'Filipinas' },
  CEB: { city: 'Cebú', country: 'Filipinas' },
  SGN: { city: 'Ho Chi Minh', country: 'Vietnam' },
  HAN: { city: 'Hanoi', country: 'Vietnam' },
  AER: { city: 'Sochi', country: 'Rusia' },
};

export function getAirportInfo(code: string): AirportInfo {
  const cleanCode = (code || '').toUpperCase();
  return AIRPORTS_MAP[cleanCode] || {
    city: cleanCode,
    country: 'Europa'
  };
}

export function getAirportCityName(code: string): string {
  return getAirportInfo(code).city;
}
