-- Create the festivals table
CREATE TABLE IF NOT EXISTS public.festivals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    country TEXT NOT NULL,
    region TEXT,
    city TEXT NOT NULL,
    description TEXT,
    dates_approx TEXT,
    rating INTEGER,
    unique_reason TEXT,
    lat FLOAT8 NOT NULL,
    lon FLOAT8 NOT NULL,
    start_month INTEGER, -- 1 to 12
    start_day INTEGER,   -- 1 to 31
    end_month INTEGER,   -- 1 to 12
    end_day INTEGER,     -- 1 to 31
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.festivals ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access
CREATE POLICY "Allow public read access for festivals" ON public.festivals
    FOR SELECT TO public USING (true);

-- Insert data
-- Note: Coordinates are approximate (center of the city)
-- Months: 1=Jan, 2=Feb, ..., 12=Dec

INSERT INTO public.festivals (name, country, region, city, description, dates_approx, rating, unique_reason, lat, lon, start_month, start_day, end_month, end_day) VALUES
('San Fermín', 'España', 'Navarra', 'Pamplona', 'La reina indiscutible. Encierros de infarto y 8 días de anarquía de blanco y rojo.', '6–14 Julio', 100, 'Encierros y ambiente inigualable.', 42.8125, -1.6458, 7, 6, 7, 14),
('Feria de Abril', 'España', 'Andalucía', 'Sevilla', 'La mayor ciudad efímera de casetas, rebujito, trajes de flamenca y caballos.', 'Abril', 98, 'Casetas y ambiente andaluz.', 37.3891, -5.9845, 4, 1, 4, 30),
('Las Fallas', 'España', 'C. Valenciana', 'Valencia', 'Arte efímero gigante, pólvora incesante (mascletás) y fuego quemando la ciudad entera.', '15-19 Marzo', 98, 'Mascletás y la Cremà.', 39.4699, -0.3763, 3, 15, 3, 19),
('Carnaval de Cádiz', 'España', 'Andalucía', 'Cádiz', 'El paraíso de la sátira. Coros, comparsas y chirigotas inundando la calle.', 'Febrero/Marzo', 97, 'Chirigotas y humor.', 36.5271, -6.2886, 2, 1, 3, 31),
('Aste Nagusia', 'España', 'País Vasco', 'Bilbao', 'Casetas (txosnas) tomando la ciudad entera. Música ininterrumpida y ambiente callejero total.', 'Agosto', 96, 'Txosnas y Marijaia.', 43.2630, -2.9350, 8, 15, 8, 25),
('La Patum', 'España', 'Cataluña', 'Berga', 'Fuego continuo en una plaza estrecha, con dragones y demonios ardiendo al ritmo de tambores.', 'Junio (Corpus)', 96, 'Fuego y misticismo.', 42.1030, 1.8463, 6, 1, 6, 30),
('Rapa das Bestas', 'España', 'Galicia', 'Sabucedo', 'Lucha cuerpo a cuerpo entre "aloitadores" y caballos salvajes para cortarles las crines. Pura adrenalina.', 'Julio', 95, 'Lucha con caballos salvajes.', 42.5855, -8.4116, 7, 1, 7, 10),
('La Tomatina', 'España', 'C. Valenciana', 'Buñol', 'La mayor guerra de tomates del planeta. Corta (dura una hora) pero intensísima.', 'Último miérc. Ago', 95, 'Guerra de tomates.', 39.4187, -0.7918, 8, 25, 8, 31),
('Semana Santa de Sevilla', 'España', 'Andalucía', 'Sevilla', 'Pasión desbordada, saetas y pasos de incalculable valor por calles estrechas.', 'Marzo/Abril', 95, 'Pasión y saetas.', 37.3891, -5.9845, 3, 20, 4, 15),
('Concurso Castells', 'España', 'Cataluña', 'Tarragona', 'Collas castelleras levantando torres humanas de hasta 10 pisos. Piel de gallina.', 'Octubre (bienal)', 95, 'Torres humanas de 10 pisos.', 41.1189, 1.2445, 10, 1, 10, 15),
('Fiestas de la Blanca', 'España', 'País Vasco', 'Vitoria-Gasteiz', 'Comienza con la "Bajada de Celedón", una explosión de puros y cava en una plaza a reventar.', '4-9 Agosto', 95, 'Bajada de Celedón.', 42.8467, -2.6716, 8, 4, 8, 9),
('Descenso del Sella', 'España', 'Asturias', 'Ribadesella', 'Competición de canoas de día, y macrofiesta al aire libre ("Las Piraguas") de noche.', '1º sáb. Agosto', 94, 'Canoas y fiesta nocturna.', 43.4624, -5.0610, 8, 1, 8, 10),
('Moros y Cristianos', 'España', 'C. Valenciana', 'Alcoy', 'Recreación histórica espectacular, trajes majestuosos y trabucos atronadores.', 'Abril', 94, 'Recreación histórica y trajes.', 38.6983, -0.4736, 4, 20, 4, 25),
('Romaría Vikinga', 'España', 'Galicia', 'Catoira', 'Desembarco vikingo real en la ría. La gente se disfraza, hay barro y el vino fluye a mares.', '1º dom. Agosto', 93, 'Desembarco vikingo.', 42.6661, -8.7236, 8, 1, 8, 7),
('Romería del Rocío', 'España', 'Andalucía', 'El Rocío', 'Miles de carretas, caballos y romeros cruzando caminos de arena hasta la aldea.', 'Mayo/Junio', 93, 'Salto de la reja y romería.', 37.1315, -6.4847, 5, 15, 6, 15),
('Caballos del Vino', 'España', 'Murcia', 'Caravaca de la Cruz', 'Caballos salvajes engalanados corriendo a toda velocidad por una cuesta entre la multitud.', '1-5 Mayo', 93, 'Carrera de caballos engalanados.', 38.1075, -1.8601, 5, 1, 5, 5),
('Feria del Caballo', 'España', 'Andalucía', 'Jerez de la Frontera', 'Casetas públicas, rebujito, y miles de caballos de pura raza paseando por un Real espectacular.', 'Mayo', 93, 'Caballos de pura raza y rebujito.', 36.6850, -6.1261, 5, 1, 5, 31),
('Batalla del Vino', 'España', 'La Rioja', 'Haro', 'Guerra de guerrillas en la montaña donde el único arma son miles de litros de vino tinto.', '29 Junio', 92, 'Guerra de vino tinto.', 42.5765, -2.8481, 6, 29, 6, 29),
('Fiestas del Pilar', 'España', 'Aragón', 'Zaragoza', 'Ofrenda floral gigante, conciertos por toda la ciudad y un fervor festivo inabarcable.', 'Octubre', 92, 'Ofrenda floral y conciertos.', 41.6488, -0.8891, 10, 1, 10, 15),
('Los Escobazos', 'España', 'Extremadura', 'Jarandilla de la Vera', 'Al caer la noche, el pueblo se lía a escobazos de fuego. Espectáculo visual increíble.', '7 Diciembre', 92, 'Escobas de fuego.', 40.1278, -5.6586, 12, 7, 12, 7),
('Carnaval de Águilas', 'España', 'Murcia', 'Águilas', '"Cascarones" (huevos de confeti), disfraces deslumbrantes y litros de "cuerva" (bebida mágica).', 'Febrero/Marzo', 92, 'Cascarones y cuerva.', 37.4063, -1.5835, 2, 1, 3, 31),
('El Cascamorras', 'España', 'Andalucía', 'Baza', 'Batalla campal de miles de personas cubiertas de aceite quemado luchando cuerpo a cuerpo.', 'Septiembre', 91, 'Aceite quemado y lucha.', 37.4907, -2.7725, 9, 6, 9, 15),
('El Cipotegato', 'España', 'Aragón', 'Tarazona', 'Lluvia masiva de tomates de todo el pueblo persiguiendo a un arlequín.', '27 Agosto', 91, 'Lluvia de tomates al arlequín.', 41.9044, -1.7248, 8, 27, 8, 27),
('Tamborrada', 'España', 'País Vasco', 'San Sebastián', '24 horas ininterrumpidas de redobles de tambor y barriles por toda la ciudad.', '20 Enero', 90, '24h de tambores.', 43.3183, -1.9812, 1, 20, 1, 20),
('Carnaval del Toro', 'España', 'C. y León', 'Ciudad Rodrigo', 'El único carnaval de España que gira en torno al toro, mezclando disfraces con encierros.', 'Febrero/Marzo', 90, 'Carnaval con encierros.', 40.5976, -6.5342, 2, 1, 3, 31),
('Fiestas de La Paloma', 'España', 'Madrid', 'Madrid', 'El casticismo madrileño llevado a la calle. Chotis, limonada, calor y verbenas.', 'Agosto', 90, 'Chotis y verbenas castizas.', 40.4168, -3.7038, 8, 10, 8, 15),
('Bando de la Huerta', 'España', 'Murcia', 'Murcia', 'La huerta toma la ciudad en un desfile masivo, con comida y bebida en las calles.', 'Primavera', 90, 'Desfile de la huerta.', 37.9922, -1.1307, 3, 20, 4, 30),
('Fiesta de los Patios', 'España', 'Andalucía', 'Córdoba', 'Cientos de patios privados decorados con miles de macetas abren sus puertas al público.', 'Mayo', 90, 'Patios llenos de flores.', 37.8882, -4.7794, 5, 1, 5, 20),
('Carnaval de Badajoz', 'España', 'Extremadura', 'Badajoz', 'Fiesta de Interés Internacional. Calles abarrotadas, murgas y comparsas espectaculares.', 'Febrero', 90, 'Murgas y comparsas.', 38.8794, -6.9706, 2, 1, 2, 28),
('Fiestas de Gràcia', 'España', 'Cataluña', 'Barcelona', 'Los vecinos transforman las calles del barrio en mundos fantásticos con decorados hechos a mano.', 'Mediados Agosto', 90, 'Calles decoradas a mano.', 41.3851, 2.1734, 8, 15, 8, 21),
('Carreras de Caballos', 'España', 'Andalucía', 'Sanlúcar de Barrameda', 'Espectaculares carreras de caballos pura sangre galopando por la playa al atardecer.', 'Agosto', 90, 'Carreras en la playa.', 36.7782, -6.3531, 8, 1, 8, 31),
('Fiestas de San Juan', 'España', 'C. y León', 'Soria', 'Seis días de anarquía, charangas, peñas y encierros de toros. El secreto mejor guardado de Castilla.', 'Junio', 90, 'Encierros y peñas.', 41.7667, -2.4667, 6, 20, 6, 30),
('Festes del Tura', 'España', 'Cataluña', 'Olot', 'Fuego, gigantes, farándula y encierros nocturnos en la capital volcánica de Cataluña. Muy intensa.', 'Septiembre', 90, 'Gigantes y encierros nocturnos.', 42.1810, 2.4894, 9, 1, 9, 10),
('Entierro de la Sardina', 'España', 'Murcia', 'Murcia', 'Cabalgata loquísima nocturna donde desde las carrozas se lanzan miles de juguetes al público.', 'Primavera', 89, 'Lanzamiento masivo de juguetes.', 37.9922, -1.1307, 3, 20, 4, 30),
('Antzar Eguna', 'España', 'País Vasco', 'Lekeitio', 'Jóvenes colgados de una cuerda sobre el agua intentando decapitar a un ganso (hoy de goma).', 'Principios Sept.', 89, 'Jóvenes sobre el ganso.', 43.3621, -2.5034, 9, 1, 9, 5),
('Los Empalaos', 'España', 'Extremadura', 'Valverde de la Vera', 'Sobrecogedor: penitentes caminan descalzos y en silencio atados fuertemente a un madero de arado.', 'Semana Santa', 89, 'Penitencia extrema.', 40.1228, -5.3678, 3, 20, 4, 15),
('La Vijanera', 'España', 'Cantabria', 'Silió', 'El primer carnaval de Europa. Ritos paganos celtas, hombres con pieles y mucha mitología.', '1º dom. Enero', 88, 'Ritos paganos celtas.', 43.1411, -3.9911, 1, 1, 1, 7),
('Danza de los Zancos', 'España', 'La Rioja', 'Anguiano', 'Jóvenes del pueblo se lanzan girando a toda velocidad por una cuesta empedrada subidos en zancos.', 'Julio y Sept.', 88, 'Zancos por cuesta empedrada.', 42.2611, -2.7631, 7, 1, 9, 30),
('Misteri d''Elx', 'España', 'C. Valenciana', 'Elche', 'Un drama sacro-lírico espectacular cantado en el interior de una basílica. Patrimonio de la Humanidad.', 'Agosto', 88, 'Drama sacro en basílica.', 38.2667, -0.6994, 8, 14, 8, 15),
('Lunes de Aguas', 'España', 'C. y León', 'Salamanca', 'Miles de estudiantes y locales se van al río a comer "hornazo" para celebrar el fin de la Cuaresma.', 'Abril', 88, 'Comer hornazo en el río.', 40.9701, -5.6635, 4, 1, 4, 30),
('Semana Santa de Úbeda', 'España', 'Andalucía', 'Úbeda', 'Sobriedad renacentista andaluza en calles empedradas, un contraste precioso con Sevilla o Málaga.', 'Marzo/Abril', 87, 'Sobriedad renacentista.', 38.0125, -3.3703, 3, 20, 4, 15),
('Fiesta de la Arribada', 'España', 'Galicia', 'Baiona', 'El pueblo vuelve a 1493 para celebrar la llegada de la carabela Pinta. Mercado medieval épico.', 'Marzo', 87, 'Llegada de la carabela Pinta.', 42.1197, -8.8497, 3, 1, 3, 10),
('La Endiablada', 'España', 'C. La Mancha', 'Almonacid del Marquesado', 'Cientos de diablos con trajes chillones y enormes cencerros en un ruido ensordecedor.', '2-3 Febrero', 86, 'Diablos con cencerros.', 39.8242, -2.7667, 2, 2, 2, 3),
('Corpus Christi Toledo', 'España', 'C. La Mancha', 'Toledo', 'Las calles medievales se cubren de flores, tomillo y tapices antiguos. Un viaje en el tiempo.', 'Junio', 86, 'Calles cubiertas de flores.', 39.8628, -4.0273, 6, 1, 6, 30),
('Guerras Cántabras', 'España', 'Cantabria', 'Los Corrales de Buelna', 'Más de mil personas recrean las feroces batallas entre las legiones romanas y las tribus cántabras.', 'Finales Agosto', 86, 'Recreación de batallas romanas.', 43.2778, -4.0667, 8, 25, 9, 5),
('Astures y Romanos', 'España', 'C. y León', 'Astorga', 'Campamentos gigantes, desfiles y un circo romano espectacular donde luchan ambos bandos.', 'Julio', 86, 'Circo romano y campamentos.', 42.4589, -6.0561, 7, 20, 7, 31),
('Batalla de Flores Laredo', 'España', 'Cantabria', 'Laredo', 'Impresionantes carrozas decoradas íntegramente con flores naturales frescas compitiendo.', 'Agosto', 85, 'Carrozas de flores naturales.', 43.4136, -3.4167, 8, 25, 8, 31),
('Semana Santa Valladolid', 'España', 'C. y León', 'Valladolid', 'Silencio absoluto, tallas renacentistas de incalculable valor y sobriedad extrema.', 'Marzo/Abril', 85, 'Silencio y tallas renacentistas.', 41.6523, -4.7245, 3, 20, 4, 15),
('El Colacho', 'España', 'C. y León', 'Castrillo de Murcia', 'Tradición loquísima donde un diablo salta por encima de colchones llenos de bebés.', 'Junio (Corpus)', 85, 'Salto sobre bebés.', 42.2217, -4.0253, 6, 1, 6, 30),
('Cerezo en Flor', 'España', 'Extremadura', 'Valle del Jerte', 'Espectáculo natural efímero con más de un millón y medio de cerezos tiñendo el valle de blanco.', 'Marzo/Abril', 85, 'Millón y medio de cerezos.', 40.1667, -5.9167, 3, 15, 4, 15),
('Feria de Málaga', 'España', 'Andalucía', 'Málaga', 'Fiesta continua dividida en dos: "Feria de Día" en el centro histórico y "Feria de Noche" en el Real.', 'Agosto', 85, 'Feria de día y noche.', 36.7213, -4.4214, 8, 10, 8, 20),
('Bodas de Isabel', 'España', 'Aragón', 'Teruel', 'La ciudad entera retrocede al siglo XIII para recrear la trágica historia de los Amantes de Teruel.', 'Febrero', 85, 'Historia de los Amantes.', 40.3444, -1.1069, 2, 15, 2, 20),
('San Juan A Coruña', 'España', 'Galicia', 'A Coruña', 'Las playas arden en la noche más corta del año con cientos de hogueras simultáneas.', '23 Junio', 85, 'Hogueras en la playa.', 43.3623, -8.4115, 6, 23, 6, 23),
('Arde Lucus', 'España', 'Galicia', 'Lugo', 'Recreación histórica inmersiva. La ciudad amurallada vuelve al Imperio Romano: circos y legiones.', 'Junio', 85, 'Ciudad romana amurallada.', 43.0125, -7.5556, 6, 1, 6, 30),
('Carnaval de Lantz', 'España', 'Navarra', 'Lantz', 'Rito pagano ancestral en el bosque donde atrapan y queman al bandido "Miel Otxin".', 'Febrero', 85, 'Quema de Miel Otxin.', 42.9961, -1.6067, 2, 1, 2, 28),
('Luces de Navidad Vigo', 'España', 'Galicia', 'Vigo', 'La ciudad entera se convierte en un parque temático navideño con millones de luces LED y norias.', 'Dic/Enero', 85, 'Millones de luces LED.', 42.2406, -8.7207, 12, 1, 1, 10),
('Fiesta del Orujo', 'España', 'Cantabria', 'Potes', 'Alambiques en plena calle destilando aguardiente tradicional en un entorno único en los Picos de Europa.', 'Noviembre', 85, 'Destilación de aguardiente.', 43.1539, -4.6231, 11, 1, 11, 15),
('Fiesta del Pulpo', 'España', 'Galicia', 'O Carballiño', 'La mayor exaltación gastronómica del pulpo á feira de toda España.', 'Agosto', 80, 'Gastronomía del pulpo.', 42.4308, -8.0772, 8, 1, 8, 15),
('San Isidro', 'España', 'Madrid', 'Madrid', 'Chulapos en la pradera, rosquillas, organillos y tradición castiza en honor al patrón.', 'Mayo', 80, 'Tradición castiza.', 40.4168, -3.7038, 5, 15, 5, 15),
('San Juan Barcelona', 'España', 'Cataluña', 'Barcelona', 'Pirotecnia continua, hogueras y coca de Sant Joan por todos los barrios y playas de la ciudad.', '23 Junio', 80, 'Pirotecnia y coca.', 41.3851, 2.1734, 6, 23, 6, 23),
('Festival de Jerez', 'España', 'Andalucía', 'Jerez de la Frontera', 'El epicentro del baile y el cante flamenco mundial. Mucha pasión y duende.', 'Febrero', 75, 'Flamenco mundial.', 36.6850, -6.1261, 2, 1, 3, 15),
('Fiestas de Almansa', 'España', 'C. La Mancha', 'Almansa', 'Espectaculares recreaciones de Moros y Cristianos a los pies de un imponente castillo medieval.', 'Mayo', 70, 'Moros y Cristianos en castillo.', 38.8694, -1.0972, 5, 1, 5, 6),
('Trashumancia', 'España', 'Madrid', 'Madrid', 'Contraste radical: miles de ovejas cruzando por el asfalto del centro moderno de la capital.', 'Octubre', 70, 'Ovejas en el centro.', 40.4168, -3.7038, 10, 15, 10, 31),
('Toro de la Vega', 'España', 'C. y León', 'Tordesillas', 'Festejo taurino de origen medieval con un torneo por el campo (actualmente sin muerte pública).', 'Septiembre', 65, 'Torneo medieval taurino.', 41.5008, -4.9997, 9, 1, 9, 15),
('Fêtes de Bayonne', 'Francia', 'Nueva Aquitania', 'Bayona', 'Más de un millón de personas vestidas de blanco y rojo tomando las calles. Fiesta inagotable.', 'Julio', 95, 'Millón de personas de blanco.', 43.4933, -1.4750, 7, 20, 7, 31),
('Día de la Bastilla', 'Francia', 'Isla de Francia', 'París', 'Desfiles militares colosales en los Campos Elíseos y fuegos artificiales épicos en la Torre Eiffel.', '14 Julio', 95, 'Desfiles militares y fuegos.', 48.8566, 2.3522, 7, 14, 7, 14),
('Féria de Dax', 'Francia', 'Nueva Aquitania', 'Dax', 'Al nivel de Bayona. La ciudad termal entera se viste de blanco y rojo, con corridas y charangas continuas.', 'Mediados Agosto', 94, 'Blanco y rojo en ciudad termal.', 43.7089, -1.0519, 8, 10, 8, 15),
('Féria de Pentecostés', 'Francia', 'Occitania', 'Nimes', 'Casetas, música y tauromaquia en un ambiente brutal, ¡todo alrededor de un anfiteatro romano intacto!', 'Mayo/Junio', 93, 'Fiesta en anfiteatro romano.', 43.8367, 4.3601, 5, 15, 6, 15),
('Féria de Béziers', 'Francia', 'Occitania', 'Béziers', 'Más de un millón de personas, caballos, casetas y mucha juerga callejera de inspiración española.', 'Mediados Agosto', 93, 'Juerga de inspiración española.', 43.3442, 3.2158, 8, 10, 8, 15),
('Carnaval de Niza', 'Francia', 'Provenza-Alpes', 'Niza', 'Carrozas inmensas, cabezudos y la famosa y elegante "Batalla de las Flores" en la Costa Azul.', 'Febrero', 92, 'Batalla de las Flores.', 43.7102, 7.2620, 2, 1, 2, 28),
('Fêtes de la Madeleine', 'Francia', 'Nueva Aquitania', 'Mont-de-Marsan', 'El equivalente azul y blanco de San Fermín. Encierros, fiesta masiva en la calle y mucha tradición gascona.', 'Julio', 91, 'Azul y blanco y encierros.', 43.8908, -0.4994, 7, 15, 7, 25),
('Fuegos de la Cité', 'Francia', 'Occitania', 'Carcasona', 'Uno de los espectáculos pirotécnicos más bellos del mundo sobre una ciudadela medieval amurallada.', '14 Julio', 90, 'Pirotecnia en ciudadela medieval.', 43.2131, 2.3536, 7, 14, 7, 14),
('Pentecôtavic', 'Francia', 'Occitania', 'Vic-Fezensac', 'Locura colectiva en este pequeño pueblo que se llena de miles de personas y decenas de "bandas" (charangas).', 'Mayo', 90, 'Locura con charangas.', 43.7589, 0.3031, 5, 15, 5, 31),
('Féria de Céret', 'Francia', 'Occitania', 'Céret', 'A los pies del Pirineo, feria taurina y callejera muy intensa donde el catalán y el francés se mezclan.', 'Julio', 89, 'Mezcla catalana y francesa.', 42.4842, 2.7486, 7, 1, 7, 15),
('Fêtes de St-Vincent', 'Francia', 'Occitania', 'Collioure', 'A un paso de Cataluña. Fuegos artificiales espectaculares en la bahía, sardanas y barcas tradicionales.', 'Mediados Agosto', 89, 'Fuegos en la bahía.', 42.5250, 3.0833, 8, 14, 8, 18),
('Feria de Arlés', 'Francia', 'Provenza-Alpes', 'Arlés', 'Toros y fiesta callejera que cobra una dimensión mística al realizarse en un anfiteatro romano del s. I.', 'Abril', 89, 'Toros en anfiteatro del s. I.', 43.6767, 4.6281, 4, 1, 4, 30),
('Fiesta del Pimiento', 'Francia', 'Nueva Aquitania', 'Espelette', 'Un pueblo precioso que se tiñe de rojo secando miles de pimientos en las fachadas.', 'Último fin. Oct.', 88, 'Pueblo teñido de rojo.', 43.3408, -1.4475, 10, 25, 10, 31),
('Fiesta del Limón', 'Francia', 'Provenza-Alpes', 'Menton', 'Construyen monumentos inmensos hechos exclusivamente con toneladas de limones y naranjas reales.', 'Febrero', 88, 'Monumentos de limones.', 43.7744, 7.4975, 2, 1, 2, 28),
('Carnaval de Limoux', 'Francia', 'Occitania', 'Limoux', 'El carnaval más largo del mundo. Fiestas de máscaras y bandas tradicionales tocando cada fin de semana.', 'Enero-Marzo', 88, 'Carnaval más largo del mundo.', 43.0531, 2.2172, 1, 1, 3, 31),
('Fêtes Saint-Louis', 'Francia', 'Occitania', 'Sète', 'Justas medievales en toda regla... ¡pero luchando sobre barcas de remos en los canales del puerto!', 'Agosto', 87, 'Justas sobre barcas.', 43.4022, 3.6939, 8, 20, 8, 25),
('Fête de l''Ours', 'Francia', 'Occitania', 'Prats-de-Mollo-la-Preste', 'Hombres manchados de hollín persiguen y marcan a la multitud simulando osos en plena montaña fronteriza.', 'Febrero', 86, 'Hombres oso con hollín.', 42.4042, 2.4792, 2, 1, 2, 28),
('Fête des Lumières', 'Francia', 'Auvernia-Ródano', 'Lyon', 'Toda la ciudad se transforma con espectaculares instalaciones y proyecciones de luz y videoarte.', 'Diciembre', 85, 'Instalaciones de luz y video.', 45.7640, 4.8357, 12, 5, 12, 10),
('Fête du Jasmin', 'Francia', 'Provenza-Alpes', 'Grasse', 'Batallas de flores donde los bomberos locales rocían a la multitud con agua perfumada de jazmín.', 'Agosto', 85, 'Agua perfumada de jazmín.', 43.6589, 6.9261, 8, 1, 8, 5),
('Festival de Aviñón', 'Francia', 'Provenza-Alpes', 'Aviñón', 'El teatro y las artes escénicas se apoderan de las calles y del histórico Palacio de los Papas.', 'Julio', 80, 'Artes en Palacio de los Papas.', 43.9483, 4.8061, 7, 1, 7, 31),
('Festa de São João', 'Portugal', 'Región Norte', 'Oporto', 'Locura colectiva: la gente va por la calle golpeándose cariñosamente en la cabeza con martillos de plástico.', '23-24 Junio', 96, 'Martillos de plástico.', 41.1579, -8.6291, 6, 23, 6, 24),
('Santo António', 'Portugal', 'Gran Lisboa', 'Lisboa', 'Los barrios históricos (Alfama, Bairro Alto) se llenan de guirnaldas, olor a sardinas asadas y marchas.', '12-13 Junio', 94, 'Guirnaldas y sardinas asadas.', 38.7223, -9.1393, 6, 12, 6, 13),
('Queima das Fitas', 'Portugal', 'Centro', 'Coimbra', 'La mayor fiesta universitaria de Europa. Fado en la calle, desfiles de carrozas y juerga sin fin.', 'Mayo', 92, 'Mayor fiesta universitaria.', 40.2033, -8.4103, 5, 1, 5, 15),
('Viagem Medieval', 'Portugal', 'Norte', 'Santa Maria da Feira', 'La recreación histórica medieval inmersiva más grande de Europa, tomando el castillo y todo el casco antiguo.', 'Agosto', 91, 'Inmersión medieval gigante.', 40.9250, -8.5417, 8, 1, 8, 15),
('Feira do Cavalo', 'Portugal', 'Alentejo', 'Golegã', 'El pueblo huele a castañas asadas y se llena de los mejores caballos lusitanos desfilando de noche.', 'Noviembre', 90, 'Caballos lusitanos nocturnos.', 39.4000, -8.4833, 11, 1, 11, 15),
('Carnaval de Ovar', 'Portugal', 'Centro', 'Ovar', 'Carnaval repleto de color, ritmo y tradiciones, famoso por sus espectaculares desfiles y "matrafonas".', 'Febrero', 89, 'Desfiles y matrafonas.', 40.8586, -8.6231, 2, 1, 2, 28),
('Carnaval Torres Vedras', 'Portugal', 'Centro', 'Torres Vedras', 'El carnaval "más portugués". Nada de samba: sátira política pura, cabezudos inmensos y desmadre.', 'Febrero', 88, 'Sátira política y desmadre.', 39.0917, -9.2597, 2, 1, 2, 28),
('FMM Sines', 'Portugal', 'Alentejo', 'Sines', 'Un espectacular festival de Músicas del Mundo que llena de ritmo el castillo y las calles frente al mar.', 'Julio', 88, 'Música del mundo en castillo.', 37.9561, -8.8697, 7, 20, 7, 31),
('Romaria da Agonia', 'Portugal', 'Región Norte', 'Viana do Castelo', 'Devoción marinera, tapices de sal en las calles y mujeres luciendo kilos de oro tradicional al cuello.', 'Agosto', 85, 'Mujeres con kilos de oro.', 41.6933, -8.8328, 8, 15, 8, 22),
('NOS Alive', 'Portugal', 'Gran Lisboa', 'Lisboa', 'Aunque es un festival de música comercial, es uno de los mejores de Europa con un ambiente brutal.', 'Julio', 85, 'Festival de música TOP.', 38.7223, -9.1393, 7, 10, 7, 15),
('Festa dos Tabuleiros', 'Portugal', 'Centro', 'Tomar', 'Espectáculo visual único: mujeres desfilando con enormes columnas de pan y flores sobre sus cabezas.', 'Julio (cada 4 a.)', 85, 'Columnas de pan y flores.', 39.6036, -8.4111, 7, 1, 7, 10),
('Carnaval de Encamp', 'Andorra', 'Encamp', 'Encamp', 'Famoso por el tradicional "Ball de l''Ossa" (baile de la osa) y los contrabandistas. Pura sátira andorrana.', 'Febrero', 75, 'Ball de l''Ossa.', 42.5361, 1.5833, 2, 1, 2, 28),
('Festival de Jazz Andorra', 'Andorra', 'Escaldes-Engordany', 'Escaldes-Engordany', 'Música internacional al aire libre en un entorno montañoso y termal espectacular.', 'Julio', 75, 'Jazz en entorno montañoso.', 42.5083, 1.5417, 7, 1, 7, 31),
('Festa Major Sant Julià', 'Andorra', 'Sant Julià de Lòria', 'Sant Julià de Lòria', 'La fiesta mayor más animada del país con pasacalles, gigantes y la histórica danza de la Marratxa.', 'Julio', 70, 'Danza de la Marratxa.', 42.4639, 1.4917, 7, 20, 7, 31),
('Fallas de Andorra', 'Andorra', 'Andorra la Vella', 'Andorra la Vella', 'Tradición pirenaica de hacer rodar fuego ("falles") por las calles de la capital del principado.', 'Junio', 60, 'Fuego rodando por las calles.', 42.5064, 1.5211, 6, 23, 6, 23),
('Festa Major Andorra la Vella', 'Andorra', 'Andorra la Vella', 'Andorra la Vella', 'La celebración central del Principado con bailes tradicionales, gigantes y folclore local.', 'Agosto', 55, 'Folclore local central.', 42.5064, 1.5211, 8, 1, 8, 10);
